language: node_js
node_js:
- stable
before_install:
- npm install grunt-cli -g
addons:
  sauce_connect:
    username: jbeard4
  jwt:
    secure: SUs3rFtjK+CnAhLU79pVwzzC0VhjPmHsv0cy8Zl5qJXSAQe5yBW7cCSVJHWJvb7fw2a9kpE0tPmj7V4CBi8VWnvOsRou6DsY4Ar0tdjO7yIo740XcV6WgRFyNfUtgDTbLBOn9+jiHerAMs0hW0Y5Y6Jb3fb6wYg6riMXO5rMyy0=
