language: node_js
node_js:
- stable
before_install:
- npm install grunt-cli -g
addons:
  sauce_connect:
    username: jbeard4
  jwt:
    secure: S2xdvBw6jAQJj0C+B1dAfjddCkNWQn0I9ZABqaksgmptdzhzDPkeKILVMZSTjQifcOBhRo+PGHkdoion6DNItHhtURh8LokAFpYzlse56TovTimmVkgqCUQ46VX5pJC9gm4d+iiIgYKvxAD310NwriUELkFwPjPYKNASCNZMsWg=
