language: node_js
node_js:
  - stable
before_install:
  - npm install grunt-cli -g
addons:
  sauce_connect:
    username: "jbeard4"
  jwt:
    secure: PbQLq/uecF7vElS0h9RtvLp9U43dSzg7z4IAkttmyxxMqGCxKTsloRrcfFS7MFmXxjMFe+7rDWeFQoUtd7sNyB159hre8xjH5WF0oAf6M2xnUSZUU9DkjK84HW2DKf+RFQHu2bUKX4qh8lzMkhIAmrtBjYCWJ8kkgzxHqj6G42Q=
